### PR TITLE
Speed up CI by using ninja and parallel build

### PR DESCRIPTION
**Pull request by ylz-at**

### CODE REVIEW

**Comment by ylz-at** [comment]
I see build time reduce from 14-20 min to 7-8 min on windows, which looks promising.

**Comment by ylz-at** [comment]
I see some speed up among windows jobs, it takes around 10 min to finish now.

But some jobs hanging for over 2h🤔.

**Comment by asuessenbach** [comment]
@ylz-at Do you want to continue with this PR?

**Comment by ylz-at** [comment]
@asuessenbach I didn't figure out what is the issue with ninja. I can close this if you need and reopen it when I have a valid solution.

**Pull request closed without merging**
