### PR TITLE
Fix std::hash specializations for null-terminated strings

### PR DESCRIPTION
**Pull request by amaiorano**
Instead of hashing the pointer, hash the string contents.

Fixes: https://github.com/KhronosGroup/Vulkan-Hpp/issues/1169

### CODE REVIEW

**Comment by asuessenbach** [comment]
Your change looks great! Thanks for your contribution.

**Comment by asuessenbach** [comment]
No idea, what's going wrong here with the CI.
Would you mind to re-trigger it by pushing your changes again?

**Comment by amaiorano** [comment]
I rebased on latest master. Let's see if the CI runs now.

**Comment by asuessenbach** [comment]
One thing that came to my mind right now: With your change, std::hash and operator==() would behave differently (on structures containing null-terminated strings, of course).
In your test case, appInfo1 and appInfo2 would give the same hash but would not be equal. Which is allowed, but probably not expected.
That is, I think, operator==() should be extended to also compare null-terminated string (and array of null-terminated string) members of structures.

**Comment by amaiorano** [comment]
> That is, I think, operator==() should be extended to also compare null-terminated string (and array of null-terminated string) members of structures.

I agree, that would make the most sense. I think we'd want operator==() to be used for value-equality, not reference-equality -- for the latter, you could always compare the addresses of the objects. Is this something you can take care of? Or perhaps open a GitHub issue for?

**Pull request merged**
