### PR TITLE
Generalize ArrayProxy and ArrayProxyNoTemporaries constructors

### PR DESCRIPTION
**Pull request by nisse-work**
Add new constructors that accept any vector-like type (with
compatible .data() and .size() methods). Replaces the more specific
constructors accepting std::array, std::vector and std::span.

### CODE REVIEW

**Comment by nisse-work** [comment]
Main motivation for this change is to be able to have types like absl::InlinedVector implictly convert to ArrayProxy/ArrayProxyNoTemporaries.

**Comment by asuessenbach** [comment]
That's a great move!
Thanks for providing this PR.

**Comment by nisse-work** [comment]
Any action needed on my part? I see that all windows ci builds were cancelled (why?), while it seems the others succeeded.

**Comment by asuessenbach** [comment]
No idea what happened there.
Restarting the CI builds were successfull -> merging.

**Pull request merged**
