### PR TITLE
Support compilation with VK_NO_PROTOTYPES defined

### PR DESCRIPTION
**Pull request by res2k**
Some third-party libraries includes `vulkan.h` with `VK_NO_PROTOTYPES` defined (e.g. Qt).
Currently, to use Vulkan-Hpp with these libraries you need to include the Vulkan and certain Qt headers in the correct order.
This patch avoids this hassle by supporting compilation with VK_NO_PROTOTYPES defined.

This works by adding checks for `VK_NO_PROTOTYPES` and disables code that relies on the prototypes:
`DispatchLoaderStatic` and certain initializations of `DispatchLoader`.

This also means that you _need_ to manually provide a Dispatcher (`DispatchLoaderDynamic` or somethinh custom) for all Vulkan-Hpp calls; but presumably you're using some kind of dynamic dispatching anyway if you haven't got the prototypes.

### CODE REVIEW

**Comment by mtavenrath** [comment]
@res2k Thank you for your contribution. We plan to merge your change, but have to ask you to add the newly generated vulkan.hpp to this PR.

**Comment by res2k** [comment]
> add the newly generated vulkan.hpp to this PR.

Sure, is on branch.

**Comment by Carandiru0** [comment]
This screws up the usage of Volk for me. 
I have simply exposed the DispatchLoaderStatic by removing the new #ifdefs that surrounded it. And deleted the NeedsExplicitDispatchLoader typedef to get it working again
Using latest version of Volk and have predefined VK_NO_PROTOTYPES

DispatchLoaderStatic, in this case, maps to the functions defined in Volk nicely, I do not link with the vulkan.lib static library.

. This regression should be reverted or make the changes as stated above.

Attached changed vulkan.hpp that has me compiling again. Thanks.

[vulkan.zip](https://github.com/KhronosGroup/Vulkan-Hpp/files/3591290/vulkan.zip)

**Comment by res2k** [comment]
Can you be more specific than "screws up"?

**Comment by res2k** [comment]
Okay, I took a look at what Volk does:
1. `#define`s `VK_NO_PROTOTYPES`
2. Includes `vulkan.h`
3. Defines it's own Vulkan "functions" (pointers actually)

So the simplest solution is to `#undef`ine `VK_NO_PROTOTYPES` after Volk made it's own function definitions. Arguably, that would also be a more consistent state of affairs - there _are_ prototype-compatible definitions available, but currently the macro says there aren't.

Anyway, such an `#undef VK_NO_PROTOTYPES` could either happen in Volk itself (you'd need to file a PR there) or in your own code (after including `volk.h`, before `vulkan.hpp`).

**Pull request merged**
